### ISSUE TITLE
[p]rolebind issues (role hierarchy)

### ISSUE THREAD

**Issue by teddyrasmussen** [mikeshardmind/SinbadCogs#218] opened 2020-06-03 22:34 UTC
When I do [p]rolebind, (with all the correct arguments), I get 'Cannot do that. Discord role hierarchy applies here'. The bot has the administrator permission, and also has the role I am trying to assign. I have tried using the role id and channel id.

**Comment by teddyrasmussen** [comment] 2020-06-03 22:43
https://gyazo.com/2d99f0f415d2f4b9f2cd99c902abc538
https://gyazo.com/c49076979db7cfd5288b19dc1ba3ea5a
https://gyazo.com/2d99f0f415d2f4b9f2cd99c902abc538

**Comment by mikeshardmind** [comment] 2020-06-04 15:38
I can't reproduce this, and there was a [commit](https://github.com/mikeshardmind/SinbadCogs/commit/53771fac4dd2747bc76a1994c37dd7432efa89d4) specifically designed to bypass a known issue with discord.py's role cache.

**Comment by Helinos** [comment] 2020-06-07 02:28
I'm also having this issue.

**Comment by mikeshardmind** [comment] 2020-06-07 09:40
As I can't reproduce this issue, I've gone ahead with improving the error messages slightly. If after updating you are having issues that you don't think you should be having, please include the cog version, bot version, and details of the failure.

**Comment by Vedinsoh** [comment] 2020-06-07 18:03
I'm having the same issue, but with the [p]roleunbind command. Bot's role, as well as mine are way higher in the hierarchy than the role I'm attempting to unbind, but bot keeps giving the following error:
> Can't do that. Discord role hierarchy applies here.

**Comment by mikeshardmind** [comment] 2020-06-07 20:02
Again, please provide enough information to confirm this isn't an outdated code issue. The cog version should display in help for the cog.

**Comment by Vedinsoh** [comment] 2020-06-07 20:07
> Again, please provide enough information to confirm this isn't an outdated code issue. The cog version should display in help for the cog.

Cog 330.2.1, bot 3.3.8

**Comment by mikeshardmind** [comment] 2020-06-07 20:09
Outdated cog version, the latest version should provide more information in failure cases.

**Comment by Vedinsoh** [comment] 2020-06-07 20:11
I have updated the cog, although I've already manually removed the bind I wanted from the cog settings.json file.

**Comment by mikeshardmind** [comment] 2020-06-07 20:30
If you've manually touched the settings file, no help will be provided. Red's config isn't something people should mess with manually.

For anyone *else* with this issue still, please confirm that it is happening on cog version 320.2.2+ (visible in help), the error message which is shown, the order of the roles in the server, the command, the roles the bot has, and the roles the author has.

As this is working as intended for multiple servers right now, I'm trying to determine if this is a configuration issue, or if there may be something else happening.

**Comment by teddyrasmussen** [comment] 2020-06-07 20:36
Cog Version: 330.2.2Red Version: 3.3.8Error: You can't give away roles which are not below your top role.I have the role I am trying to assign, and so does the bot. The role is below my top role. I have restarted the bot, and it still does not work.Role order: https://gyazo.com/ac91babf284d826a22a903322187c6ea https://gyazo.com/49ed0269626be749282bb1390038c47bBot roles: https://gyazo.com/0536a5543dbfbe4199f36e4e0cc11429Author roles: https://gyazo.com/531c729cb45278db788b0ea24e5b2bc7Message: https://gyazo.com/f7cb1f44d81aab689c3ca8ce63357f7e Sent from Mail for Windows 10 From: Michael HSent: Sunday, June 7, 2020 2:30 PMTo: mikeshardmind/SinbadCogsCc: LordWaffle27; AuthorSubject: Re: [mikeshardmind/SinbadCogs] [p]rolebind issues (role hierarchy) (#218) If you've manually touched the settings file, no help will be provided. Red's config isn't something people should mess with manually.For anyone else with this issue still, please confirm that it is happening on cog version 320.2.2+ (visible in help), the error message which is shown, the order of the roles in the server, the command, the roles the bot has, and the roles the author has.As this is working as intended for multiple servers right now, I'm trying to determine if this is a configuration issue, or if there may be something else happening.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mikeshardmind** [comment] 2020-06-07 20:51
The bot seems to be out of sync with discord about members (this is unrelated to the known issue with the member cache and role order, this involves gateway sent events)

I've also received info from another developer since this started which might support this hypothesis, but I'm going to have to look into something a bit more and reach out to discord as well to be certain.

**Comment by Flame442** [comment] 2020-06-07 20:55
<https://github.com/mikeshardmind/SinbadCogs/blob/8db6f783609bd84c1a431fcf0ff5413b0ff99a66/rolemanagement/utils.py#L84-L90>
Not quite sure if this is the issue happening here, but this line is `if (not A) or (B)`, which means that if the invoker is the bot owner, they will ALWAYS trip this exception.

**Comment by mikeshardmind** [comment] 2020-06-07 21:11
issues with the API are confirmed right now, but this probably isn't the issue (what flame put above is)

Will be pushing a fix after confirming there wasn't anything else going on.

**Comment by mikeshardmind** [comment] 2020-06-07 21:15
Okay, thank you everyone for the info on this; It helped get this solved prior to when I would have been able to sit down and look in detail. 

Fixed in: 97eb146

**Closed as completed by mikeshardmind** 2020-06-07 21:15 UTC
Labels: bug

**Comment by teddyrasmussen** [comment] 2020-06-07 22:33
I had my friend try to do the command. He has admin permissions, and also the role I was trying to assign, yet it did not respond, or add the reaction. The cog still is loaded, and the bot was responding to other commands. I think this might be the issue that flame stated, but also related to the API.
